### ISSUE TITLE
running  puthon setup.py develop  has error  setuptools.sandbox.UnpickleableException: DistutilsSetupError

### ISSUE THREAD

**Issue by bestzaa486** [manahl/arctic#112]
```
trove@controller:~/trove$ sudo python setup.py develop
running develop
running egg_info
writing pbr to trove.egg-info/pbr.json
writing requirements to trove.egg-info/requires.txt
writing trove.egg-info/PKG-INFO
writing top-level names to trove.egg-info/top_level.txt
writing dependency_links to trove.egg-info/dependency_links.txt
writing entry points to trove.egg-info/entry_points.txt
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no files found matching 'trove/db/sqlalchemy/migrate_repo/versions/*.sql'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'trove.egg-info/SOURCES.txt'
running build_ext
Creating /home/trove/.local/lib/python2.7/site-packages/trove.egg-link (link to .)
Adding trove 5.0.0.0rc2.dev5 to easy-install.pth file
Installing trove-guestagent script to /home/trove/.local/bin
Installing trove-fake-mode script to /home/trove/.local/bin
Installing trove-api script to /home/trove/.local/bin
Installing trove-taskmanager script to /home/trove/.local/bin
Installing trove-mgmt-taskmanager script to /home/trove/.local/bin
Installing trove-conductor script to /home/trove/.local/bin
Installing trove-manage script to /home/trove/.local/bin

Installed /home/trove/trove
Processing dependencies for trove==5.0.0.0rc2.dev5
Searching for oslo.db>=4.1.0
Reading https://pypi.python.org/simple/oslo.db/
Best match: oslo.db 4.6.0
Downloading https://pypi.python.org/packages/source/o/oslo.db/oslo.db-4.6.0.tar.gz#md5=54cc0c2c152ae60272803c797450cda4
Processing oslo.db-4.6.0.tar.gz
Writing /tmp/easy_install-7NOJiq/oslo.db-4.6.0/setup.cfg
Running oslo.db-4.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7NOJiq/oslo.db-4.6.0/egg-dist-tmp-3P1hmr
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/trove/trove/.eggs/pbr-1.8.1-py2.7.egg/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/home/trove/trove/.eggs/pbr-1.8.1-py2.7.egg/pbr/util.py", line 245, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config)
  File "/home/trove/trove/.eggs/pbr-1.8.1-py2.7.egg/pbr/util.py", line 379, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 132, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    pbr=True)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/develop.py", line 34, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/develop.py", line 133, in install_for_development
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 717, in process_distribution

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 850, in install_eggs

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1078, in build_and_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1064, in run_setup

  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 246, in run_setup
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 166, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 141, in resume
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 154, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 243, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 273, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 242, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-7NOJiq/oslo.db-4.6.0/setup.py", line 29, in <module>
    pbr=True)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 272, in __init__
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in finalize_options
  File "/home/trove/trove/.eggs/pbr-1.8.1-py2.7.egg/pbr/core.py", line 117, in pbr
    'Error parsing %s: %s: %s' % (path, e.__class__.__name__, e))
setuptools.sandbox.UnpickleableException: DistutilsSetupError('Error parsing /tmp/easy_install-7NOJiq/oslo.db-4.6.0/setup.cfg: TypeError: dist must be a Distribution instance',)
```

**Comment by bmoscon** [comment]
this traceback is not from arctic, its from openstack/trove. closing.
