### ISSUE TITLE
arctic decompression 

### ISSUE THREAD

**Issue by jamesblackburn** [manahl/arctic#296]
#### Arctic Version

```
1.32.0
```

#### Description of problem and/or code sample that reproduces the issue

Arctic no longer allows decompression empty strings...

```
from arctic._compression import compress, decompress
decompress(compress(''))
Traceback (most recent call last):
  File "/users/is/ahlpypi/egg_cache/i/ipython-3.2.0_1_ahl1-py2.7.egg/IPython/core/interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-7d13efc43bf6>", line 1, in <module>
    decompress(compress(''))
  File "/users/is/ahlpypi/egg_cache/a/arctic-1.32.0-py2.7-linux-x86_64.egg/arctic/_compression.py", line 70, in decompress
    return _get_lib().decompress(_str)
  File "_compress.pyx", line 121, in _compress.decompress (src/_compress.c:2159)
Exception: Error decompressing
```

**Comment by bmoscon** [comment]
fixed
