### ISSUE TITLE
install AttributeError: module object has no attribute Distutils

### ISSUE THREAD

**Issue by zoe0316** [manahl/arctic#375]
#### Arctic Version

```
# 1.46.0
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Centos 6.5 and Python 2.7.13

#### Description of problem and/or code sample that reproduces the issue

Traceback (most recent call last):
  File "setup.py", line 138, in <module>
    "Topic :: Software Development :: Libraries",
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/site-packages/setuptools/dist.py", line 323, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/site-packages/setuptools/dist.py", line 392, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load
  1 # vim: set fileencoding=utf-8 sw=4 ts=4 et :
    return self.resolve()
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/quant/.pyenv/versions/2.7.13/lib/python2.7/site-packages/setuptools_cython.py", line 12, in <module>
    print(Cython.Distutils.build_ext)
AttributeError: 'module' object has no attribute 'Distutils'

**Comment by zoe0316** [comment]
[https://github.com/greenm01/poly2tri/issues/32](url)

as the poly2tri issues said, fix is to comment out 

if  'Cython' in sys.modules:
    del sys.modules['Cython']
