### ISSUE TITLE
Using write_metadata with PickleStore read corruption

### ISSUE THREAD

**Issue by dimosped** [manahl/arctic#561]
#### Arctic Version

```
1.65
```

#### Arctic Store

```
VersionStore with PickleStore
```

#### Description of problem and/or code sample that reproduces the issue

```
import arctic

class Foo(object):
    def __init__(self, x):
        self.x = x

ac = arctic.Arctic('localhost:27017')
ac.initialize_library('my_test_lib', arctic.VERSION_STORE)
mylib = ac['my_test_lib']

mylib.write(symbol='symX', data=Foo(99), metadata={'key': 'key'})
mylib.write_metadata(symbol='symX', metadata={'key2': 'key'})
mylib.read('symX')
```

Raises EOFError:

```
Traceback (most recent call last):
  File "/python/i/ipython-5.2.2-py2.7.egg/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-67-8945034ee714>", line 17, in <module>
    mylib.read('symX')
  File "build/bdist.linux-x86_64/egg/arctic/store/version_store.py", line 341, in read
    date_range=date_range, read_preference=read_preference, **kwargs)
  File "build/bdist.linux-x86_64/egg/arctic/store/version_store.py", line 386, in _do_read
    data = handler.read(self._arctic_lib, version, symbol, from_version=from_version, **kwargs)
  File "build/bdist.linux-x86_64/egg/arctic/store/_pickle_store.py", line 57, in read
    return pickle_compat_load(io.BytesIO(data))
  File "/python/p/pandas-0.16.2+ahl1-py2.7-linux-x86_64.egg/pandas/compat/pickle_compat.py", line 116, in load
    return up.load()
  File "/python/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/python/lib/python2.7/pickle.py", line 886, in load_eof
    raise EOFError
EOFError
```

**Comment by dimosped** [comment]
This happens if:
  - Using the VersionStore
  - Using first a write, and then write_metadata
  - The object written as data has to fail to be encoded as bson. This line should throw exception and version['blob'] to be set with _MAGIC_CHUNKEDV2:
     https://github.com/manahl/arctic/blob/master/arctic/store/_pickle_store.py#L63
  - Read the symbol data


The solution is to prefer the version['base_version_id'] while reading, rather than the version['_id']
