### ISSUE TITLE
sharding not enabled on chunkstore

### ISSUE THREAD

**Issue by harishmk** [manahl/arctic#594]
#### Arctic Version

```
arctic==1.68.0
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Red Hat Enterprise Linux Server release 7.3 (Maipo)
`Linux XXXXX 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

#### Description of problem and/or code sample that reproduces the issue

sharding is enabled on version store libraries  on creation.
chunkstore libraries do not have sharding enabled.
trying to enable sharding using the utility fails:

```
$ python -m arctic.scripts.arctic_enable_sharding --host ...
Enabling-sharding: arctic.ctest on mongo nj1prdnixotk03:27016
2018-08-02 15:00:05,205 Hash sharding 'symbol' on: arctic.ctest
Traceback (most recent call last):
  File "/home/USER/.edm/envs/edm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/USER/.edm/envs/edm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/arctic-1.68.0-py2.7-linux-x86_64.egg/arctic/scripts/arctic_enable_sharding.py", line 40, in <module>
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/arctic-1.68.0-py2.7-linux-x86_64.egg/arctic/scripts/arctic_enable_sharding.py", line 36, in main
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/arctic-1.68.0-py2.7-linux-x86_64.egg/arctic/_util.py", line 58, in enable_sharding
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/USER/.edm/envs/edm/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: can't shard collection 'arctic.ctest' with unique index on { sy: 1, sh: 1 } and proposed shard key { symbol: "hashed" }. Uniqueness can't be maintained unless shard key is a prefix
```

**Comment by bmoscon** [comment]
fixed on master
