### ISSUE TITLE
Install of 1.16.0 failed

### ISSUE THREAD

**Issue by llazzaro** [manahl/arctic#65]
pip install arctic==1.16.0

```
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-OQyXkO/arctic/setup.py", line 31, in <module>
        long_description = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by llazzaro** [comment]
For the record : pip install git+https://github.com/manahl/arctic.git works, but no from pypi

**Comment by AdrianTeng** [comment]
LGTM
