### ISSUE TITLE
Fix Benchmark runner

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#694]
benchmarks seem to be broken at the moment. Tried running them with asv but got:
```
   STDOUT -------->
   
   STDERR -------->
   Traceback (most recent call last):
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 1169, in <module>
       main()
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 1162, in main
       commands[mode](args)
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 879, in main_discover
       list_benchmarks(benchmark_dir, fp)
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 864, in list_benchmarks
       for benchmark in disc_benchmarks(root):
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 762, in disc_benchmarks
       for module in disc_modules(root_name, ignore_import_errors=ignore_import_errors):
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 744, in disc_modules
       for item in disc_modules(name, ignore_import_errors=ignore_import_errors):
     File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 732, in disc_modules
       module = import_module(module_name)
     File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
       __import__(name)
     File "/users/is/skhare/git/arctic_shashank/benchmarks/benchmarks.py", line 43, in <module>
       s_compress = [gen_series_compressible(rows) for rows in TEST_SIZES]
     File "/users/is/skhare/git/arctic_shashank/benchmarks/benchmarks.py", line 36, in gen_series_compressible
       return pd.Series(data=data, index=index)
     File "/users/is/skhare/git/arctic_shashank/env/b8a89d02ecf8cf65a0ce1bec4918bbdf/lib/python2.7/site-packages/pandas/core/series.py", line 262, in __init__
       .format(val=len(data), ind=len(index)))
   ValueError: Length of passed values is 1, index implies 1000
```

**Comment by shashank88** [comment]
I think they were always broken, I fixed it with:
-    data = [d * rows]
+    data = [d] * rows
in line 32. Will send a PR for it. 
After fixing this I get another error due to an argument being unicode instead of string.

**Comment by shashank88** [comment]
Now the benchmarks seem to be broken with a str vs unicode error. Debugging

**Comment by shashank88** [comment]
```[  0.00%] ··· Importing benchmark suite failed (skipping all benchmarks).
[  0.00%] ···· asv: benchmark runner crashed
               Traceback (most recent call last):
                 File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/runner.py", line 755, in preimport
                   out = self._send_command({'action': 'preimport'})
                 File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/runner.py", line 786, in _send_command
                   s.sendall(struct.pack('<Q', len(msg)))
               TypeError: Struct() argument 1 must be string, not unicode

[ 50.00%] ··· asv: forkserver:
[ 50.00%] ··· Traceback (most recent call last):
                File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 1169, in <module>
                  main()
                File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 1162, in main
                  commands[mode](args)
                File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 990, in main_run_server
                  read_size, = struct.unpack('<Q', recvall(conn, 8))
                File "/users/is/skhare/git/arctic_shashank/.venv/lib/python2.7/site-packages/asv/benchmark.py", line 225, in recvall
                  "(size {}, got only {!r})".format(size, data))
              RuntimeError: did not receive data from socket (size 8, got only '')
```
