### ISSUE TITLE
VersionStore does not persist timezone info

### ISSUE THREAD

**Issue by js190** [manahl/arctic#727]
#### Arctic Version

```
v1.73.0 and HEAD
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

ubuntu

#### Description of problem and/or code sample that reproduces the issue

When writing dataframe indexed with DateTime index (df.index.name == 'date') with timezone (UTC in this case) i get a bson error:

`bson.errors.InvalidDocument: Cannot encode object: datetime.timezone.utc`

however, if i reset the index so that 'date' col is in the dataframe i can write the df but the timezone is not persisted.

Is this a known issue?

Cheers

**Comment by jamesblackburn** [comment]
This should work - see for example the integration tests that do this:
https://github.com/manahl/arctic/blob/master/tests/integration/store/test_pandas_store.py#L107

Can you provide a minimal code example showing the issue?

**Comment by cmorgan** [comment]
To chime in here, this is something I noticed happening when using real data, having coded a similar unittest as above which did not display the issue. I worked around it by making my arctic client tz_localize utc on reads.

**Comment by shashank88** [comment]
Closing this since no activity / reproducible unit test for this. Please reopen if needed

**Comment by PatternMatching** [comment]
Code snippet to reproduce:

```
#!/usr/bin/env python

import logging

import arctic
import pymongo
import pandas as pd
import numpy as np
import pytz

import tsg.core.tsArctic as ts_arctic


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logging.info("Arctic version: {}".format(arctic.__version__))
    logging.info("Pymongo version: {}".format(pymongo.__version__))
    logging.info("Pandas version: {}".format(pd.__version__))
    logging.info("NumPy version: {}".format(np.__version__))
    logging.info("pytz version: {}".format(pytz.__version__))

    cxn = ts_arctic.get_arctic_connection()
    utc_idx = pd.date_range('2019-10-16 00:00:00', periods=6, freq='H', tz='UTC')
    utc_data = pd.Series([1, 2, 3, 4, 5, 6], index=utc_idx)
    cxn['hennip-vs'].write('tz-bug-symbol', utc_data)
```

Logging and stack trace:

```
INFO:root:Arctic version: 1.75.0
INFO:root:Pymongo version: 3.7.2
INFO:root:Pandas version: 0.24.2
INFO:root:NumPy version: 1.16.2
INFO:root:pytz version: 2018.7
INFO:arctic.arctic:Connecting to mongo: *REDACTED*
INFO:arctic.arctic:Mongo Quota: arctic.hennip-vs 0.000 / 10 GB used
INFO:arctic.serialization.numpy_records:Index has no name, defaulting to 'index'
INFO:arctic.serialization.numpy_records:Series has no name, defaulting to 'values'
Traceback (most recent call last):
  File "arctic_vs_tz_bug.py", line 25, in <module>
    cxn['hennip-vs'].write('tz-bug-symbol', utc_data)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\arctic\decorators.py", line 49, in f_retry
    return f(*args, **kwargs)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\arctic\store\version_store.py", line 664, in write
    self._insert_version(version)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\arctic\store\version_store.py", line 529, in _insert_version
    mongo_retry(self._versions.insert_one)(version)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\arctic\decorators.py", line 49, in f_retry
    return f(*args, **kwargs)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\collection.py", line 693, in insert_one
    session=session),
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\collection.py", line 607, in _insert
    bypass_doc_val, session)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\collection.py", line 595, in _insert_one
    acknowledged, _insert_command, session)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\mongo_client.py", line 1248, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\mongo_client.py", line 1201, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\collection.py", line 590, in _insert_command
    retryable_write=retryable_write)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\pool.py", line 584, in command
    self._raise_connection_failure(error)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\pool.py", line 745, in _raise_connection_failure
    raise error
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\network.py", line 114, in command
    codec_options, ctx=compression_ctx)
  File "C:\miniconda\envs\ts-venv-prod\lib\site-packages\pymongo\message.py", line 679, in _op_msg
    flags, command, identifier, docs, check_keys, opts)
bson.errors.InvalidDocument: Cannot encode object: <UTC>
```

**Comment by yaniboshev** [comment]
The problem persist.

`arctic version = 1.79.3
pandas = 1.0.3
numpy = 1.16.2
pymongo = 3.7.1
os = Ubuntu 18.04.4 LTS
arctic store = VersionStore`
