### ISSUE TITLE
UTC timezone failed on write, where my old data were all utc

### ISSUE THREAD

**Issue by rick-sanchez-c137** [manahl/arctic#734]
#### Arctic Version

```
# 1.7.4.0
```

#### Arctic Store

```
# VersionStore,
```

#### Platform and version

Debian 9

#### Description of problem and/or code sample that reproduces the issue

lib.write("test", ddf)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/arctic/decorators.py", line 49, in f_retry
    return f(*args, **kwargs)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/arctic/store/version_store.py", line 664, in write
    self._insert_version(version)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/arctic/store/version_store.py", line 529, in _insert_version
    mongo_retry(self._versions.insert_one)(version)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/arctic/decorators.py", line 49, in f_retry
    return f(*args, **kwargs)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/collection.py", line 693, in insert_one
    session=session),
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/collection.py", line 607, in _insert
    bypass_doc_val, session)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/collection.py", line 595, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1248, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1201, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/collection.py", line 590, in _insert_command
    retryable_write=retryable_write)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/pool.py", line 584, in command
    self._raise_connection_failure(error)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/pool.py", line 745, in _raise_connection_failure
    raise error
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/network.py", line 114, in command
    codec_options, ctx=compression_ctx)
  File "/home/mortysmith_89/miniconda3/envs/kk/lib/python3.7/site-packages/pymongo/message.py", line 679, in _op_msg
    flags, command, identifier, docs, check_keys, opts)
bson.errors.InvalidDocument: Cannot encode object: <UTC>

**Comment by bmoscon** [comment]
probably need a more complete example with some data that reproduces the issue.

Pandas recently changed how timezones are stored on datetimeindexes, so I'm guessing its related to that.

**Comment by rick-sanchez-c137** [comment]
Guess you are right, Bryant. pandas used to set tz to "UTC" during pd,to_datetime() based on format. Now to keep things persistent, I have up update all old stuff to "GMT0". darn it
