### ISSUE TITLE
running setup.py without dependencies pre-installed gives errors

### ISSUE THREAD

**Issue by bmoscon** [manahl/arctic#84]
```
Installed /home/bryant/arctic
Processing dependencies for arctic==1.19.0
Searching for tzlocal
Reading https://pypi.python.org/simple/tzlocal/
Best match: tzlocal 1.2
Downloading https://pypi.python.org/packages/source/t/tzlocal/tzlocal-1.2.tar.gz#md5=2e36ceb1260bf1233ed2f018a1df536e
Processing tzlocal-1.2.tar.gz
Writing /tmp/easy_install-971xQ2/tzlocal-1.2/setup.cfg
Running tzlocal-1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-971xQ2/tzlocal-1.2/egg-dist-tmp-WFrc5P
Moving tzlocal-1.2-py2.7.egg to /home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages
Adding tzlocal 1.2 to easy-install.pth file

Installed /home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/tzlocal-1.2-py2.7.egg
Searching for pymongo>=3.0
Reading https://pypi.python.org/simple/pymongo/
Best match: pymongo 3.2
Downloading https://pypi.python.org/packages/source/p/pymongo/pymongo-3.2.tar.gz#md5=463b4d325d8fb4070c04f15391b457bf
Processing pymongo-3.2.tar.gz
Writing /tmp/easy_install-UxPSJi/pymongo-3.2/setup.cfg
Running pymongo-3.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UxPSJi/pymongo-3.2/egg-dist-tmp-A3Utib
Traceback (most recent call last):
  File "setup.py", line 131, in <module>
    "Topic :: Software Development :: Libraries",
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/develop.py", line 33, in run
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/develop.py", line 132, in install_for_development
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 719, in process_distribution
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 846, in resolve
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1091, in best_match
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1103, in obtain
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 639, in easy_install
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 669, in install_item
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 852, in install_eggs
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 1080, in build_and_install
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 1066, in run_setup
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 242, in run_setup
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 166, in save_modules
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 141, in resume
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 154, in save_modules
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 239, in run_setup
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 269, in run
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 238, in runner
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-UxPSJi/pymongo-3.2/setup.py", line 309, in <module>
    
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/bdist_egg.py", line 151, in run
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 185, in run
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 208, in find_sources
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 292, in run
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 321, in add_defaults
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/sdist.py", line 132, in add_defaults
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/command/build_ext.py", line 420, in get_source_files
    self.check_extensions_list(self.extensions)
  File "/home/bryant/anaconda2/envs/arctic/lib/python2.7/distutils/command/build_ext.py", line 362, in check_extensions_list
    ("each element of 'ext_modules' option must be an "
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple",)
```

If I install pymongo with conda, and run it again, I get a similar issue with LZ4. If I install that and run again, it works without issue.

**Comment by jamesblackburn** [comment]
I wonder if this is related to #2 

The circle CI build installs the dependencies manually because of a memory leak in setuptools.

**Comment by bmoscon** [comment]
closing as a duplicate of #2. Looking around online I see many many mainstream libraries working around setuptools because of similar issues.
