### ISSUE TITLE
Setup.py install will fail if dependencies are not already installed 

### ISSUE THREAD

**Issue by Winterflower** [manahl/arctic#9]
OS where problem was observed: Ubuntu 14.04 and OSX Yosemite
Setuptools versions: 18.0.1 and 17.1.1

Installing Arctic dependencies (such as PyMongo) causes the entire system to crash. 
On the other hand, if dependencies are installed before running 

``` python
python setup.py install
```

everything is fine. 

A snippet from the stacktrace:

```
Processing dependencies for arctic==1.0.0
Searching for pymongo>=3.0
Reading https://pypi.python.org/simple/pymongo/
Best match: pymongo 3.0.3
Downloading https://pypi.python.org/packages/source/p/pymongo/pymongo-3.0.3.tar.gz#md5=0425d99c2a453144b9c95cb37dbc46e9
Processing pymongo-3.0.3.tar.gz
Writing /tmp/easy_install-MK91Bw/pymongo-3.0.3/setup.cfg
Running pymongo-3.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MK91Bw/pymongo-3.0.3/egg-dist-tmp-usQbt3
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    "Topic :: Software Development :: Libraries",
  File "/home/winterflower/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/winterflower/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/winterflower/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 380, in run
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 610, in easy_install
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 661, in install_item
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 709, in process_distribution
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve

  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match

  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain

  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 629, in easy_install
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 659, in install_item
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 842, in install_eggs
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 1070, in build_and_install
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/command/easy_install.py", line 1056, in run_setup
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/sandbox.py", line 240, in run_setup
  File "/home/winterflower/anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/sandbox.py", line 193, in setup_context
  File "/home/winterflower/anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/sandbox.py", line 152, in save_modules
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/sandbox.py", line 126, in __exit__
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/winterflower/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/setuptools/sandbox.py", line 110, in dump
```

I believe the problem is caused by a bug in setuptools. The trace I get from running the setup.py for Arctic is identical to the one attached in [this bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1209018) report. Enthought/Enable has also had a similar issue with setuptools (see [this issue](https://github.com/enthought/enable/issues/179))

I ran top while running the setup.py script, and the resident size (RES) jumps to 2.0G as soon as the script begins installing the first dependency. I believe memory leaks like this have been observed in setuptools before.

**Comment by jamesblackburn** [comment]
We see this in the CircleCI build - we've been working around it by manual `pip install` some of the packages before the build.  From your links it looks like this may have been fixed?  It needs some digging to see if we a newer version works better...

**Comment by bmoscon** [comment]
This is no longer an issue for a few reasons:

1) We have Arctic wheels now for the supported platforms and versions.
2) We fixed the issue where Cython had to be pre-installed.
3) I used a clean env and did the same command `python setup.py install` and it no longer times out or fails.
